import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Homepage from "./components/Homepage";
import { SessionProvider } from "next-auth/react";
import Provider from "./components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Friends Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        {children}
        hello
        </Provider>
        </body>
    </html>
  );
}
